FROM debian:11.6

RUN apt-get update\
    && apt-get install --no-install-recommends -y python3-pip git gnupg build-essential make docker.io sudo \
    && pip install ansible \
    && apt-get clean \
    && apt-get install -y openjdk-17-jre

COPY . /ansible/playbooks/
RUN ansible-playbook -i /ansible/playbooks/inventory /ansible/playbooks/jenkins.yml \
    && usermod -aG docker jenkins

#USER jenkins
WORKDIR /var/lib/jenkins

ENV JENKINS_HOME=/var/lib/jenkins
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

CMD /usr/bin/java -Djava.awt.headless=true -Djenkins.install.runSetupWizard=false -Dhudson.security.csrf.GlobalCrumbIssuerConfiguration.DISABLE_CSRF_PROTECTION=true -jar /usr/share/java/jenkins.war --webroot=/var/cache/jenkins/war --httpPort=8080
