---
- name: H-tasks
  hosts: master
  become: yes

  tasks:

  - name: Set alias ll
    replace:
      path: /home/vagrant/.bashrc
      regexp: "^#alias ll='ls -l'$"
      replace: "alias ll='ls -la'"

  - name: install packages
    become: yes
    apt:
      pkg:
      - vim
      - mc
      - sshpass
      state: present

  - name: Install Apache
    apt:
      name: apache2
      state: present

  - name: Install PHP
    apt:
      name: php7.4
      state: present
      
  - name: Changing perm of "/var/www/", adding "rwx"
    file:
      path: /var/www
      mode: 'o+w'  

  - name: Create dir php/
    file:
      path: /var/www/php
      state: directory 

  - name: Changing perm of "/var/www/php/", adding "w"
    file:
      path: /var/www/php
      mode: 'o+w'

  - name: Add listen 81-th port
    shell: echo 'Listen 81' >> /etc/apache2/ports.conf

  - name: Modification 000-default.conf
    shell: sh -c "echo '<VirtualHost *:81>\n 
      ServerAdmin webmaster@localhost\n
      DocumentRoot /var/www/php\n
      ErrorLog ${APACHE_LOG_DIR}/error.log\n
      CustomLog ${APACHE_LOG_DIR}/access.log combined\n
      </VirtualHost>' >> /etc/apache2/sites-enabled/000-default.conf"
  
  - name: CURL file html
    shell: 'curl -o /var/www/html/index.html https://raw.githubusercontent.com/Fenikks/devops-files/master/03-lxc/files/index.html'
    
  - name: CURL file html
    shell: 'curl -o /var/www/php/index.php https://raw.githubusercontent.com/Fenikks/devops-files/master/03-lxc/files/index.php'

  - name: Reload service apache, in all cases
    service:
      name: apache2
      state: reloaded

  - name: Enable service apache, and not touch the state
    service:
      name: apache2
      enabled: yes    
      




