Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian11"
  config.vm.synced_folder  ".", "/vagrant", disabled: false

  config.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
  end

  config.vm.define "master", primary: true do |master|
      master.vm.network "private_network", ip: "10.0.3.101"

      master.vm.provision "shell", inline: <<-SHELL
          apt-get update
          apt-get install -y vim mc ansible sshpass
          sed -i "s/^#alias ll='ls -l'\$/alias ll='ls -la'/g" /home/vagrant/.bashrc
          echo "alias ll='ls -la'" >> /root/.bashrc
      SHELL
  end

  config.vm.define "slave", primary: true do |slave|
      slave.vm.network "private_network", ip: "10.0.3.102"
      
      slave.vm.provision "shell", inline: <<-SHELL
          sed -i "s/^#alias ll='ls -l'\$/alias ll='ls -la'/g" /home/vagrant/.bashrc
          sed -i "s/^PasswordAuthentication no\$/PasswordAuthentication yes/g" /etc/ssh/sshd_config
          service sshd restart
      SHELL
  end
end