FROM golang:1.16 as builder
RUN apt-get update && apt-get install -y git && apt-get install -y build-essential
RUN mkdir -p /app/src
WORKDIR /app/src/word-cloud-generator
RUN git clone https://github.com/Fenikks/word-cloud-generator.git
RUN make -f Makefile
RUN cp ./artifacts/ /app/res/word-cloud-generator/artifacts/word-cloud-generator

FROM alpine:latest
COPY --from=builder word-cloud-generator /word-cloud-generator
CMD ["./word-cloud-generator"] 