FROM golang:1.16 as builder
RUN apt-get update && apt-get install -y git && apt-get install -y build-essential
RUN mkdir -p /app/src
WORKDIR /app/src/
RUN git clone https://github.com/Fenikks/word-cloud-generator.git
WORKDIR /app/src/word-cloud-generator
RUN make 

FROM alpine:latest
COPY --from=builder /app/src/word-cloud-generator/artifacts/linux/ .
CMD ./word-cloud-generator