version: '3'
services:
  nexus:
    container_name: nexus
    build:
      context: ./nexus
      dockerfile: dockerfile-nexus
    ports:
      - 81:8081
    network_mode: host

  jenkins:
    container_name: jenkins
    build:
      context: ./jenkins
      dockerfile: dockerfile-jenkins
    ports:
      - 80:8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ws:/var/lib/jenkins/workspace/
    network_mode: host

volumes:  
  ws:  

#networks:
#  hw-10: