version: '3'
services:
  jenkins:
    container_name: jenkins
    build:
      context: ./jenkins
      dockerfile: dockerfile-jenkins
    ports:
      - 80:8080
    networks:
      - hw-10
  nexus:
    container_name: nexus
    build:
      context: ./nexus
      dockerfile: dockerfile-nexus
    ports:
      - 81:8081
    networks:
      - hw-10
networks:
  hw-10: 