---
- name: general
  hosts: 
  - master
  - slave1
  - slave2
  become: yes

  tasks:

  - name: Add Puppet Labs GPG key.
    rpm_key:
      key: https://yum.puppet.com/RPM-GPG-KEY-puppet-20250406
      state: present

  - name: install packages
    yum:
      name: https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
      state: present
    become: true  

- name: Master provision
  hosts: master

  tasks:

  - name: install packages
    become: yes
    yum: 
      pkg:
      - git
      - sshpass
      - puppetserver
      state: latest

- name: Slave's provision
  hosts: 
    - slave1
    - slave2

  tasks:

  - name: install packages
    become: yes
    yum:
      pkg:
      - puppet-agent
      state: present        