Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8s"
  config.vm.synced_folder  ".", "/vagrant", disabled: false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus   = 1
  end

  config.vm.define "master.puppet", primary: true do |master|
    master.vm.network "private_network", ip: "169.254.20.101"

    master.vm.hostname = "master.puppet"
    master.vm.provider("virtualbox") { |vb| vb.memory = 1024 }

    master.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yaml"
      ansible.limit = 'master'
      ansible.inventory_path = "inventory"
    end  
  end

  config.vm.define "slave1.puppet" do |slave|
    slave.vm.network "private_network", ip: "169.254.20.102"
    slave.vm.hostname = "slave1.puppet"

    slave.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yaml"
      ansible.limit = 'slave1'
      ansible.inventory_path = "inventory"
    end    
  end

  config.vm.define "slave2.puppet" do |slave|
    slave.vm.network "private_network", ip: "169.254.20.103"
    slave.vm.hostname = "slave2.puppet"

    slave.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yaml"
      ansible.limit = 'slave2'
      ansible.inventory_path = "inventory"
    end  
  end

end