Vagrant.configure("2") do |config|
    config.vm.box = "generic/centos8s"
    config.vm.synced_folder  ".", "/vagrant", disabled: false
  
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
    end

    config.vm.define "slave1.puppet" do |slave1|
        slave1.vm.network "private_network", ip: "169.254.20.102"
        slave1.vm.hostname = "slave1.puppet"

        slave1.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "master.yaml"
            ansible.become = true
        end
    end

    config.vm.define "slave2.puppet" do |slave2|
        slave2.vm.network "private_network", ip: "169.254.20.103"
        slave2.vm.hostname = "slave2.puppet"

        slave2.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "master.yaml"
            ansible.become = true
        end
    end

    config.vm.define "master.puppet", primary: true do |master|
        master.vm.network "private_network", ip: "169.254.20.101"
        master.vm.hostname = "master.puppet"

        master.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "master.yaml"
            ansible.limit = 'all'
            ansible.inventory_path = "inventory"
        end
    end
end