Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8"
  config.vm.synced_folder  ".", "/vagrant", disabled: false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus   = 1
  end

  config.vm.define "master.puppet", primary: true do |master|
    master.vm.network "private_network", ip: "169.254.20.1"

    master.vm.hostname = "master.puppet"
    master.vm.provider("virtualbox") { |vb| vb.memory = 1024 }

    master.vm.provision :shell, inline: <<-SHELL
      yum install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
      yum install -y vim mc
      yum install -y --downloadonly puppetserver git
      yum install python3-pip -y
      python3 -m pip install ansible
    SHELL

    master.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yaml"
      ansible.limit = 'all'
      ansible.inventory_path = "inventory"
    end

  end

  config.vm.define "slave1.puppet" do |slave1|
    slave1.vm.network "private_network", ip: "169.254.20.2"
    slave1.vm.hostname = "slave1.puppet"

    slave1.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yaml"
      ansible.become = true
    end

    slave1.vm.provision :shell, inline: <<-SHELL
      yum install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
      yum install -y vim mc
      yum install -y --downloadonly puppet-agent
    SHELL
  end

  config.vm.define "slave2.puppet" do |slave2|
    slave2.vm.network "private_network", ip: "169.254.20.3"
    slave2.vm.hostname = "slave2.puppet"

    slave2.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yaml"
      ansible.become = true
    end

    slave2.vm.provision :shell, inline: <<-SHELL
      yum install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
      yum install -y vim mc
      yum install -y --downloadonly puppet-agent
    SHELL
  end

end