---
# Jenkins should not be running while we write configuration files, otherwise
# otherwise some data might be overwritten when it restarts.
- include_tasks: "{{ jenkins_install_via }}/stop.yaml"

- name: Set JENKINS_HOME
  lineinfile:
    create: true
    dest: "/lib/systemd/system/jenkins.service"
    line: "JENKINS_HOME={{ jenkins_home }}"
    regexp: '^JENKINS_HOME='
    state: present

- name: Set Jenkins port for HTTP
  lineinfile:
    dest: /lib/systemd/system/jenkins.service
    regexp: '^HTTP_PORT='
    line: "HTTP_PORT={{ jenkins_port }}"

- name: Set Jenkins port for HTTPS
  lineinfile:
    dest: /lib/systemd/system/jenkins.service
    regexp: '^HTTPS_PORT='
    insertafter: '^HTTP_PORT='
    line: "HTTPS_PORT={{ jenkins_port_https }}"

- name: Set Jenkins Java command line options
  lineinfile:
    dest: /lib/systemd/system/jenkins.service
    regexp: '^JAVA_ARGS='
    line: "JAVA_ARGS=\"{{ jenkins_java_opts }}\""

- name: Ensure correct ownership of JENKINS_HOME directory
  file:
    path: "{{ jenkins_home }}"
    owner: "{{ jenkins_config_owner }}"
    group: "{{ jenkins_config_group }}"
    mode: 0755
    state: directory