---
- name: Start Jenkins service
  service:
    name=jenkins
    state=restarted
    enabled=yes

- name: Wait for Jenkins to start up
  uri:
    url: http://localhost:8080
    status_code: 200
    user: "admin"
    password: "admin"
    timeout: 5
    force_basic_auth: yes
  register: jenkins_service_status
  retries: 10
  delay: 5
  until: >
     'status' in jenkins_service_status and
     jenkins_service_status['status'] == 200

- name: Check Jenkins status
  debug:
    msg: "Jenkins status: {{ jenkins_service_status['status'] }}"

- name: Install Jenkins plugins
  jenkins_plugin:
    name: "{{ item }}"
    url_username: "admin"
    url_password: "admin"
    state: present
  with_items:
    - locale
    - golang
    - github-branch-source:1696.v3a_7603564d04
    - git
    - workflow-multibranch
    - nexus-artifact-uploader
  when: jenkins_service_status['status'] == 200
 
- name: Copy go-plugins config file
  copy:
    src: "{{ jenkins_plugins_via }}/go.xml"
    dest: "{{ jenkins_home }}/org.jenkinsci.plugins.golang.GolangBuildWrapper.xml"

- name: Copy locale-plugins config file
  copy:
    src: "{{ jenkins_plugins_via }}/locale.xml"
    dest: "{{ jenkins_home }}/locale.xml"

- name: reload systemd
  become: yes
  command: systemctl daemon-reload        

- name: Jenkins reload
  ansible.builtin.systemd:
    name: jenkins.service
    state: restarted        