name: Docker Image CI

on: workflow_dispatch

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile.multi --tag my-image-name:wcg
