FROM debian:11.6
COPY . /ansible/playbooks/
RUN apt update && apt install -y ansible && apt clean
RUN ansible-playbook -i /ansible/playbooks/inventory /ansible/playbooks/nexus1.yml
CMD /opt/nexus-latest/bin/nexus run