FROM debian:11.6

RUN apt-get update\
    && apt-get install --no-install-recommends -y python3-pip git gnupg rsync \
    && pip install ansible jmespath \
    && apt-get clean \
    && apt-get install -y openjdk-17-jre

COPY . /ansible/playbooks/
RUN ansible-playbook -i /ansible/playbooks/inventory /ansible/playbooks/nexus.yml
CMD /opt/nexus-latest/bin/nexus run