version: '3'
services:
  nexus:
    container_name: nexus
    build:
      context: ./nexus
      dockerfile: dockerfile-nexus1
    ports:
      - 81:8081
    networks:
      - hw-10

  jenkins:
    container_name: jenkins
    build:
      context: ./jenkins
      dockerfile: dockerfile-jenkins
    ports:
      - 80:8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ws:/var/lib/jenkins/workspace/
    networks:
      - hw-10

volumes:  
  ws:  

networks:
  hw-10: