Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian11"
  config.vm.synced_folder  ".", "/vagrant", disabled: false

  config.vm.network "forwarded_port" , guest:80, host: 8080
  
  config.vm.network "forwarded_port" , guest:81, host: 8081

  config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
  end

  config.vm.define "master", primary: true do |master|
      master.vm.network "private_network", ip: "10.0.3.103"

      master.vm.provision "ansible_local" do |ansible|
          ansible.playbook = "playbook.yaml"
          ansible.limit = 'all'
          ansible.inventory_path = "inventory"
      end
  end     
end